// packages/react-demo/src/components/MyForm.tsx
import { FC } from "react";
import { Button, Form, Input } from 'antd';
const MyForm: FC = () => {
  const [form] = Form.useForm();
  const onFinish = (values: any) => {
    console.log(values)
  }
  return (
    <div style={{ width: '300px' }}>
      <Form form={form} onFinish={onFinish}>
        <Form.Item name="input" label="react input">
          <Input />
        </Form.Item>
        <Button type="primary" htmlType="submit">click</Button>
      </Form>
    </div>
  )
}
export default MyForm;

// packages/vue2-demo/src/components/MyForm.vue
<template>
  <div class="form_container">
    <el-form :model="formInline">
      <el-form-item label="vue input">
        <el-input v-model="formInline.input" placeholder=""></el-input>
      </el-form-item>
      <el-button type="primary" @click="onSubmit">click</el-button>
    </el-form>
  </div>
</template>

<script lang="ts">
export default {
    data() {
      return {
        formInline: {
          input: '',
        }
      }
    },
    methods: {
      onSubmit() {
        console.log(this.formInline.input);
      }
    }
  }
</script>

<style scoped>
.form_container {
  width: 300px;
}
</style>
